# Generated by Django 2.1.3 on 2018-11-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='placeholder-pw', max_length=100),
        ),
    ]
